version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/" 
    schedule:
      interval: "daily" 
    commit-message:
      prefix: "maven"
    groups:
      minor-and-patch:
        patterns:
          - "*" 
        update-types:
        - "minor"
        - "patch"
